[SS-BIG-CLUSTER]
algo_type ss
sampling 10000
sensor quiet_therm
device cluster1
device_max_limit 1824000
set_point 75000
set_point_clr 70000
action_type 10000

[SS-LITTLE-CLUSTER]
algo_type ss
sampling 10000
sensor quiet_therm
device cluster0
thresholds 55000 60000 65000
thresholds_clr 52000 57000 62000
action_type 25000

[SS-GPU]
algo_type ss
sensor gpu
sampling 10000
device gpu
device_max_limit 367000000
set_point 70000
set_point_clr 60000
action_type 10000

[SS-CPU5]
algo_type ss
sampling 30
sensor cpu5
device cluster1
device_max_limit 864000
set_point 80000
set_point_clr 75000
action_type 5000

[SS-CPU4]
algo_type ss
sampling 30
sensor cpu4
device cluster1
device_max_limit 864000
set_point 80000
set_point_clr 75000
action_type 5000

[SS-CPU3]
algo_type ss
sampling 65
sensor cpu3
device cluster0
device_max_limit 864000
set_point 75000
set_point_clr 70000
action_type 5000

[SS-CPU2]
algo_type ss
sampling 65
sensor cpu2
device cluster0
device_max_limit 864000
set_point 75000
set_point_clr 70000
action_type 5000

[SS-CPU0-1]
algo_type ss
sampling 65
sensor cpu0-1
device cluster0
device_max_limit 864000
set_point 75000
set_point_clr 70000
action_type 5000

[HOTPLUG-CPU4]
algo_type monitor
sampling 1000
sensor cpu4
thresholds 85000
thresholds_clr 80000
actions hotplug_4
action_info 1

[HOTPLUG-CPU5]
algo_type monitor
sampling 1000
sensor cpu5
thresholds 85000
thresholds_clr 80000
actions hotplug_5
action_info 1

[BATTERY_MONITOR]
algo_type monitor
sampling 10000
thresholds 44000 47000 49000
thresholds_clr 42000 46000 48000
actions battery battery battery
action_info 2000 1000 500